!># fpm_release_parameters: This module was automatically generated by the fpm CI 
module fpm_release_parameters
    implicit none 
    public 
character(len=*), parameter :: fpm_version_ID = "0.7.0"
character(len=*), parameter :: fpm_version_long = "v0.7.0-66-gccf84960"
end module fpm_release_parameters
