name = "features_with_dependency"
version = "0.1.0" 
license = "MIT"
description = "Demo package testing dependency features"

[[executable]]
name = "features_with_dependency"
source-dir = "app"
main = "main.f90"

[dependencies]
# Base dependencies (none for this demo - features will add them)

[features]
# Feature that enables debug mode in the dependency
with_feat_debug.dependencies.features_demo = { path = "../features_demo", features = ["debug"] }
with_feat_debug.preprocess.cpp.macros = ["WITH_DEMO","WITH_DEBUG_DEPENDENCY"]

# Feature that enables release mode in the dependency  
with_feat_release.dependencies.features_demo = { path = "../features_demo", features = ["release"] }
with_feat_release.preprocess.cpp.macros = ["WITH_DEMO","WITH_RELEASE_DEPENDENCY"]

# Feature that enables multiple dependency features
with_feat_multi.dependencies.features_demo = { path = "../features_demo", features = ["debug", "mpi"] }
with_feat_multi.preprocess.cpp.macros = ["WITH_DEMO","WITH_MULTI_DEPENDENCY"]

# Feature for platform-specific dependency features
linux_specific.linux.dependencies.features_demo = { path = "../features_demo", features = ["linux"] }
linux_specific.preprocess.cpp.macros = ["WITH_DEMO","LINUX_FEATURES"]

# Feature combining compiler and dependency features
gfortran_optimized.gfortran.dependencies.features_demo = { path = "../features_demo", features = ["release", "gfortran"] }
gfortran_optimized.gfortran.flags = "-O3 -march=native"
gfortran_optimized.preprocess.cpp.macros = ["WITH_DEMO"]


[profiles]
debug_dep = ["with_feat_debug"]
release_dep = ["with_feat_release"]
full_test = ["with_feat_multi", "linux_specific"]
