name = "dependency_tree"
version = "0.1.0"
[build]
auto-executables=true
[dependencies]
# Request toml-f v0.3.1. 
toml-f.git = "https://github.com/toml-f/toml-f"
toml-f.tag = "v0.3.1"
# jonquil 0.2.0 requires toml-f v0.4.0. 
# Because 0.4.0 is a derived dependency, it should not be used
jonquil.git = "https://github.com/toml-f/jonquil"
jonquil.tag = "v0.2.0"
