name = "d11"

[library]
source-dir="source"

[[executable]]
name="d11"
source-dir="app"
main="d11.F90"

[profiles.debug.gfortran]
flags="-g -O2 -Dnot_defined=4"

[profiles.debug.gfortran.windows]
flags="/g /O2 /Dnot_defined=4"
