name = "hello_complex"

[library]
source-dir="source"

[[executable]]
name="say_Hello"
source-dir="apps/say_hello"
main="say_Hello.f90"

[[executable]]
name="say_goodbye"
source-dir="apps/say_goodbye"
main="say_goodbye.f90"

[[test]]
name="greet_test"
source-dir="tests/greet"
main="greet_test.f90"

[[test]]
name="farewell_test"
source-dir="tests/farewell"
main="farewell_test.f90"

[profiles.debug.gfortran.linux]
flags = '-fcheck=bounds'
files={"source/greet_m.f90"="-Wall -g -fcheck=all", "source/farewell_m.f90"="-Og"}

