name: Bug Report
description: Something is not working
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: Please include steps to reproduce your issue, provide example code snippets if possible
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behaviour
      placeholder: What did you expect to happen instead
    validations:
      required: true
  - type: input
    id: fpm-version
    attributes:
      label: Version of fpm
      placeholder: 0.4.0, 04da9a1ce99e8fce1abdb7eb9a2073f3188038ea, ...
    validations:
      required: true
  - type: input
    id: platform
    attributes:
      label: Platform and Architecture
      placeholder: MacOS/ARM, Windows, OpenBSD, ...
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      placeholder: Further relevant context, i.e. links to other issues
    validations:
      required: false
