name = "d1"

[library]
source-dir="source"

[[executable]]
name="d1"
source-dir="app"
main="d1.f90"

[profiles.debug.gfortran.linux]
flags="-g -O1"

[dependencies]
"d11" = {path = "../d11"}
"d12" = {path = "../d12"}


