name = "main_package"

[profiles.debug.gfortran]
flags="-g -Dnot_defined=1"

[profiles.debug.gfortran.windows]
flags="/g /Dnot_defined=1"

[dependencies]
"d1" = {path = "../d1"}
"d2" = {path = "../d2"}

