!> CMake staleness detection utilities
module fpm_cmake_check
    use fpm_filesystem, only: exists, read_lines
    use fpm_strings, only: string_t, fnv_1a
    use, intrinsic :: iso_fortran_env, only: int64
    implicit none
    private
    public :: compute_manifest_hash, check_cmake_staleness

contains

    !> Compute hash of fpm.toml manifest file for staleness detection
    function compute_manifest_hash(manifest_file) result(hash_str)
        character(len=*), intent(in) :: manifest_file
        character(len=:), allocatable :: hash_str

        type(string_t), allocatable :: lines(:)
        integer(int64) :: hash_val
        character(len=20) :: temp_str
        integer :: i

        ! Read manifest file content and compute hash
        if (exists(manifest_file)) then
            lines = read_lines(manifest_file)
            if (size(lines) > 0) then
                ! Hash all lines together
                hash_val = fnv_1a(lines(1)%s)
                do i = 2, size(lines)
                    hash_val = fnv_1a(lines(i)%s, hash_val)
                end do
            else
                hash_val = 0_int64
            end if
            ! Convert hash to hex string
            write(temp_str, '(z16.16)') hash_val
            hash_str = trim(adjustl(temp_str))
        else
            hash_str = "0000000000000000"
        end if
    end function compute_manifest_hash

    !> Check if CMake files are stale and need regeneration
    !> Returns .true. if CMakeLists.txt exists with fpm marker and is out of date
    function check_cmake_staleness() result(is_stale)
        logical :: is_stale

        type(string_t), allocatable :: lines(:)
        character(len=:), allocatable :: current_hash, stored_hash
        integer :: i
        logical :: has_fpm_marker, has_hash

        is_stale = .false.

        ! Check if CMakeLists.txt exists
        if (.not. exists("CMakeLists.txt")) return

        ! Read first few lines to check for fpm marker and hash
        lines = read_lines("CMakeLists.txt")
        if (size(lines) == 0) return

        ! Look for fpm marker in first line
        has_fpm_marker = .false.
        has_hash = .false.
        stored_hash = ""

        do i = 1, min(5, size(lines))  ! Check first 5 lines
            if (index(lines(i)%s, "generated by fpm") > 0) then
                has_fpm_marker = .true.
            end if
            if (index(lines(i)%s, "Manifest hash:") > 0) then
                ! Extract hash from line like "# Manifest hash: ABCD1234"
                has_hash = .true.
                stored_hash = trim(adjustl(lines(i)%s(index(lines(i)%s, "Manifest hash:") + 14:)))
            end if
        end do

        ! If not generated by fpm, don't warn
        if (.not. has_fpm_marker) return

        ! If no hash found, it's an old format - consider stale
        if (.not. has_hash) then
            is_stale = .true.
            return
        end if

        ! Compare with current manifest hash
        if (exists("fpm.toml")) then
            current_hash = compute_manifest_hash("fpm.toml")
            if (trim(stored_hash) /= trim(current_hash)) then
                is_stale = .true.
            end if
        end if

    end function check_cmake_staleness

end module fpm_cmake_check
